INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12066', 'SDK初始化失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12107', 'start方法被多次调用错误', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12117', '调用303获取视博云tenantID方法', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12118', '调用303获取视博云tenantID成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12119', '调用303获取视博云tenantID失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12021', '加载等待框失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12022', '加载自定义背景图成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12023', '加载自定义背景图失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12026', '片头预加载失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12029', '播放片头失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12010', '测速完成，起播码率上报', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12032', '测速失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12073', '调用getCid方法失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12019', '排队场景，用户选择入队', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '10039', '排队场景，用户选择不入队', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12047', '音频流连接断开', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12048', '视频流连接断开', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12042', '每固定周期帧延迟结果上报', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12116', '收到Input连接非 stopIM startIM pong的消息', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12004', '关闭自定义键位', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12005', '开启自定义键位', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12092', '点击Toolbar“卡了”按钮', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12093', '点击Toolbar“不卡”按钮', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12007', '获取自定义按键', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12043', '调用SaaS Server接口失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12060', '瘦身是否解压so库', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12061', '瘦身解压so库结果', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12062', '瘦身ijkplayer加载so库结果', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12065', '拷贝so库文件到sdcard', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12064', '拷贝so库结果', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12096', 'SaaS-WS 校验失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12113', 'countly地址给修改', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12130', '开始调用 getPublickIPV4 获取IPV4', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12131', '获取IPV4地址成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12132', '获取IPV4地址失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12300', '设备不支持', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12999', '播流统计数据上报（APP）', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12998', '云游戏失败/异常退出上报', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12306', 'QoS数据上报', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12500', 'DNS 配置', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12501', 'DNS 数据重置, 清空所有的dns cache', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12502', '开始get dns ip 地址', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12503', '获取 dns ipv4 地址成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12504', '获取 dns ipv6 地址成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12505', '获取 dns ip地址 失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12506', '解释 dns 开始', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12507', '解释 dns 完成', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12508', '优先使用ipv6地址 flag 打开', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12509', '优先使用ipv6地址 flag 关闭', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12510', 'host/ip 连接失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12511', 'websocket 地址替换成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12512', 'rtmp 地址替换成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12513', '模块错误', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12520', 'websocket连接成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12521', 'websocket连接失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13201', '连接语音通道成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13202', '连接语音通道失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13203', '收到开始录音信息', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13204', '超时未收到通道成功信息（暂定10S）', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13205', '用户允许获取麦克风', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13206', '用户拒绝获取麦克风', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13207', '收到结束录音信息', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13208', '语音通道断开', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13209', '浏览器版本不支持录音功能', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13211', 'video 视频流解码失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13214', '222接口请求失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13217', 'WEBRTC连接失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13218', 'WEBRTC重试成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13219', 'WEBRTC重试失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13220', 'WEBRTC信令服务链接超时', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13227', 'WEBRTC信令服务器已经连接再次发送join', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13231', 'WEBRTC开始重试', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13233', 'WEBRTC执行接口setRemoteDescription失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13234', 'WEBRTC创建answer成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13235', 'WEBRTC创建answer失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13237', 'WEBRTC执行setLocalDescription失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13239', 'WEBRTC执行addIceCandidate接口失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13243', 'WEBRTC收到onicecandidate事件中，candidate值为null', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13244', 'WEBRTC不支持new RTCPeerConnection()', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13245', '信令服务状态', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13246', 'sdk解码格式', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13247', '网络断开 / 连上', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13248', 'WEBRTC收到第一帧', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13249', 'WEBRTC解码完第一帧', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13250', 'WEBRTC--自身重连成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13251', 'WEBRTC--其他情况下连接成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13252', 'WEBRTC--peer状态', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13253', 'WEBRTC 收到音频信息', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13401', 'connection 创建', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13402', 'connection 关闭', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13403', 'connection 状态变化', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13404', 'connection 被选定', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13405', 'connection ping', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13406', 'connection ping 成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13407', 'connection ping 失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13408', 'connection 收到数据', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13409', '发起 binding', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13410', 'binding 成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13411', 'binding 失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13412', 'port 收到binding req', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13413', 'connection 收到binding req', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13414', 'connection 处理binding req成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13415', 'connection 处理binding req失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13416', 'connection ping失败断开', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13450', 'peer connection断开，这个event仅记录事件，不做任何处理，真正的处理在13228', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13451', 'RTC的一个connection断开后,rtc内部重连成功,仅做记录用,没有别的逻辑处理', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13452', '收到ROM端的重复OFFER,大概率是ROM端Streamer重启，或者是切换分辩率由PAAS重启了Streamer', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13453', 'qos data channel 打开', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13454', 'qos data 数据乱序', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13501', 'ping指定域名延迟数据', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13502', 'websocket心跳超时次数', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13503', 'websocket心跳超时次数达到最大值', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13504', 'sdk回调app状态值status', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13505', 'sdk回调app场景scene', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '14000', '联网错误', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '14001', 'Access长连接获取输入流', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '14002', 'Access长连接获取输出流', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '14003', 'Access长连接发送握手协议', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '14004', 'Access长连接发送心跳', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '14005', 'Access长连接下发Operation3', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '14006', 'Access长连接断开', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '14011', '获取加密key', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '14012', '加解密失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '15000', '云游戏结束时App主动调用上报', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '14020', '', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '14021', 'ping空口增加埋点', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '16002', '基于时钟校准的延迟检测 【凤凰项目】', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12201', '开始调用 手动释放cid', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12202', '手动释放cid成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12203', '手动释放cid失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13301', '请求直播', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13302', '请求直播成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13303', '请求直播失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13304', '请求停止直播', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13305', '请求停止直播成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13306', '请求停止直播失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13307', '请求授权码', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13308', '请求授权码返回成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13309', '请求授权码返回失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13310', '请求控制权', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13311', '请求控制权成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13312', '请求控制权失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13313', '通知获得控制权成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13314', '通知获得控制权失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13315', '通知失去控制权', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13321', '互换控制权成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13322', '互换控制权失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13323', '互换控制权还原成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13324', '互换控制权还原失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '14014', '量子-刷新stoken请求开始', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '14015', '量子-刷新stoken请求成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '14016', '量子-刷新stoken请求失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '15014', '量子-确认入队请求开始', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '15015', '量子-确认入队请求成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '15016', '量子-确认入队请求失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12093', '点击Toolbar“不卡”按钮', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12094', '收到Input连接 startIM', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12095', '收到Input连接 stopIM', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '19000', 'RTCTracing方法调用后事件上报', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12400', 'screenurl 为空', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12305', 'screen因无网络断开', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12306', 'QoS数据上报', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12301', '点击下载按钮', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12299', '播放状态', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12140', 'Native初始化 _native_init', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12141', '创建Native IjkMediaPlayer 成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12142', '设置流地完成 _setDataSourceAndHeaders :url', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12143', 'Native层开始加载解码 开始', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12144', 'Native层开始加载解码 结束', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12145', '初始化帧队列 完成', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12146', '初始化数据包队列 完成', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12147', '初始化时针 完成', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12148', '创创建视频刷新的线程 完成', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12149', '创建视频读取的线程 完成', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12150', '初始化视频解码器', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12151', '开始播放 ijkmp_start', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12160', 'FFmpeg开启输入流，并且读取header 开始 avformat_open_input', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12161', '协议读写 初始化URLContext与AVIOContext 开始 io_open_default', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12162', '开启 RTMP连接并验证流是否可以播放 rtmp_open', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12163', '开启tcp Socket连接 开始', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12164', '开启tcp Socket连接 成功:tcp://220.194.80.121:44743', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12165', 'rtmp握手 开始', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12166', 'rtmp握手 成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12167', '建立网络Connect连接，发送到Server 开始 gen_connect', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12168', '建立网络Connect连接，发送到Server 成功 gen_connect', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12169', '建立网络流 createStream 发送', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12170', '建立网络流 createStream 成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12171', '发送播放命令 play 开始', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12172', '发送播放命令 play 成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12173', '协议读写 初始化URLContext与AVIOContext 完成 ffio_open_whitelist 结束', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12174', 'FFmpeg开启输入流，并读取header 结束 avformat_open_input', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13316', '游戏退出', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13506', '无网络', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13701', '获取测速信息', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13702', '获取测速信息成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13703', '获取测速信息失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13704', '测速状态', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12092', '点击Toolbar“卡了”按钮', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12621', 'rom侧分享通知sdk', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12622', 'rom侧打开相册通知sdk', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12623', 'rom侧打开相册通知sdk', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12601', '开始上传', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12602', '单文件上传成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12603', '上传停止', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12604', '取消上传', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12605', '上传错误', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12606', '上传完成', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12607', '上传状态', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12608', '切换分辨率关闭 上传长连接', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12230', 'saas返回指令格式不正确', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12232', '201请求返回参数不正确', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12233', '准备游戏过程中参数校验失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12234', '因为什么原因导致没有上报16003事件', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12235', '用户点击play没有达到请求211标准', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13800', '返回流类型不一致，开始切流', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13801', '226请求成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13802', '226获取流地址成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '13803', '226获取流地址失败或者请求失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12901', '向WsServer发送数据', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12902', '向WsServer发送数据成功', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12903', '向WsServer发送数据失败', '', 'EventID');
INSERT INTO `t_dict_meta` (`module`, `dic_id`, `dic_name`, `dic_desc`, `type`) VALUES ('SDK', '12904', '接收到WsServer数据', '', 'EventID');